runtime: python311

env_variables:
  PORT: 8080
  GOOGLE_CLOUD_PROJECT: _PROJECT_ID

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 2
  memory_gb: 2

network:
  session_affinity: false