steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.minimal', '-t', 'gcr.io/$PROJECT_ID/voice-tutor-minimal', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/voice-tutor-minimal']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'voice-tutor-minimal'
    - '--image=gcr.io/$PROJECT_ID/voice-tutor-minimal'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--memory=512Mi'
    - '--cpu=1'
    - '--timeout=60'
images:
  - 'gcr.io/$PROJECT_ID/voice-tutor-minimal'